### ISSUE TITLE
pick a place inflate and closes

### ISSUE THREAD

**Issue by rgbufferchime** [vermayash8/TaskNearby#83]
i am trying to work on this but whenever i click select on map..it inflates and closes immideately

**Comment by vermayash8** [comment]
Please attach the logs here for debugging the issue.

**Comment by ksatyam59** [comment]
Actully, in the section of place picking when click on select, map opens and no autosuggetions takes place , can't get any place through searching. Finally becomes unable to select any place and going further

**Comment by vermayash8** [comment]
Hey @rgbufferchime @ksatyam59  - We've moved away from the Place Picker model that was present at the time when you reported this issue. We've built our own customer place picker widget in the app.

I'm closing this issue because I think this was resolved. Please feel free to re-open if the issue still exists.
